#!/bin/sh
_errormsg() {
	printf "Error: %s\n" "$1"
	exit 1
}

_debugmsg() {
	printf "DEBUG: %s\n" "$1"
}

[ "${1-}" = "debug" ] && DEBUG=1
[ "$(whoami)" = "root" ] || _errormsg "You are not root. Use 'sudo install.sh'"

clear
# ensure the nix daemon is running
if ! systemctl is-active nix-daemon >/dev/null; then
	printf "The nix daemon is not running, starting it now.\n"
	systemctl start nix-daemon || _errormsg "Failed to start the nix-daemon service."
fi

y_or_n() {
	[ "${1-}" ] || _errormsg "y_or_n called without prompt."
	[ "${DEFAULT-}" ] && unset DEFAULT
	MSG="$1"
	for arg in "$@"; do
		[ "$arg" = "$1" ] && continue
		ARG_NAME=$(printf "%s" "$arg" | cut -d= -f1)
		ARG_VAL=$(printf "%s" "$arg" | cut -d= -f2)
		case $ARG_NAME in
		"default") DEFAULT="$ARG_VAL" ;;
		*)
			printf "y_or_n: Unknown argument %s\n" "$arg"
			continue
			;;
		esac
	done
	case "${DEFAULT-}" in
	"yes") CONFIRMATION_TEXT="[Y/n]" ;;
	"no") CONFIRMATION_TEXT="[y/N]" ;;
	*) CONFIRMATION_TEXT="[y/n]" ;;
	esac

	while :; do
		printf "%s %s: " "$MSG" "$CONFIRMATION_TEXT"
		read -r yn

		case "${yn-}" in
		"Y" | "y") return 0 ;;
		"N" | "n") return 1 ;;
		*)
			if [ ! "${DEFAULT-}" ]; then
				printf "Not a valid response.\n"
				continue
			fi
			if [ ! "${yn-}" ]; then
				case "$DEFAULT" in
				"yes") return 0 ;;
				"no") return 1 ;;
				esac
			else
				printf "Not a valid response.\n"
			fi
			;;
		esac
	done
}

_confirm() {
	[ "${1-}" ] || _errormsg "_confirm called without a message argument."
	printf "%s" "$1"
	stty -echo -icanon min 1 time 0
	dd bs=1 count=1 >/dev/null 2>&1
	stty "${DEFAULT_TTY_SETTINGS}"
	printf "\n"
}

while ! curl -s ifconfig.me >/dev/null; do
	if y_or_n "No internet connection. Attempt to connect?" default="yes"; then
		nmtui
		clear
	else
		_errormsg "Aborted"
	fi
done

_enter_secret() {
	[ "${1-}" ] || _errormsg "_enter_secret called without a message argument."
	printf "%s" "$1" >"$(tty)"
	stty -echo
	read -r tmp
	stty "${DEFAULT_TTY_SETTINGS}"
	printf "%s" "$tmp"
	unset tmp
}

_clone_repo() {
	[ "${REPO_DIR-}" ] || _errormsg "REPO_DIR is not set. This is a bug."
	if [ -d "$REPO_DIR" ] && [ "$(ls -A "$REPO_DIR")" ]; then
		printf "\nFiles were found in the repo destination directory: %s\n" "$REPO_DIR"
		printf "This occurs if a previous installation that cloned a repo and was aborted\n"
		y_or_n "Clear the contents of $REPO_DIR and clone your repository again?" default="no" || return 0
		rm -rf "$REPO_DIR" || _errormsg "Failed to rm $REPO_DIR"
	fi

	mkdir -p "$REPO_DIR" || _errormsg "Failed to create $REPO_DIR"

	while :; do
		printf "\nEnter the url for your repository: "
		read -r REPO_URL
		if ! git ls-remote "${REPO_URL-}"; then
			printf "Could not clone the repository. Either the url entered is invalid or you do not have access permissions."
			y_or_n "Attempt to clone repository again?" default="yes" || exit 1
			continue
		fi
		break
	done

	git clone "$REPO_URL" --depth 1 "$REPO_DIR" || _errormsg "Something went wrong when pulling the repository."
}

_get_nixos_hardware_config() {
	[ "${HOST_CONFIG_DIR-}" ] || _errormsg "\nError: Hardware configuration function called without HOST_CONFIG_DIR being set. This is a bug."

	HOST_HARDWARE_CONFIG="$HOST_CONFIG_DIR/hardware-configuration.nix"
	# nuke old hardware config and regenerate. Its not supposed to be manually modified so assume the user has made no changes to it
	if [ -e "$HOST_HARDWARE_CONFIG" ]; then
		rm "$HARDWARE_CONFIG" || _errormsg "Failed to remove $HARDWARE_CONFIG"
	fi

	# generate only the kernel modules and other basic configuration as filesystems are handled by disko
	nixos-generate-config --no-filesystems --root /mnt >/dev/null || _errormsg "NixOS failed to generate the hardware report"
	# remove the generated configuration.nix as all we care about is the hardware report
	rm "$CONFIG_ROOT/configuration.nix" || _errormsg "Failed to remove $CONFIG_ROOT/configuration.nix"
	mv "$CONFIG_ROOT/hardware-configuration.nix" "$HOST_CONFIG_DIR" || _errormsg "Failed to move $CONFIG_ROOT/hardware-configuration.nix into place."

	# enable ZramSwap if the host has 4 GB or less RAM
	if [ "$(cat /proc/meminfo | grep MemTotal | cut -d: -f2 | tr -d " kB")" -le 4000000 ]; then
		printf "\nDetected a small amount of available RAM for this host.\n"
		printf "The installer will enable a module for compressed zramSwap to assist with RAM management\n"

		sed -i '$ s/.$//' "$HOST_CONFIG_DIR/configuration.nix"
		printf "zramSwap.enable = true;\n}" >>"$HOST_CONFIG_FILE"
		LOW_RAM=1
	fi

	# get the disko file in place.
	if [ ! "${DEBUG-}" ]; then
		if [ ! -e /tmp/selected-disko-config.nix ]; then
			printf "\nERROR: Neither a disko configuration file for this host nor a configuration file generated by the installer could be found.\n"
			printf "This happens when you attempt to evaluate a new configuration without formatting drives during this installation session.\n"
			printf "It can be fixed by reformatting the disks or placing a valid disko file at %s/disko.nix\n" "$HOST_CONFIG_DIR"
			exit 1
		fi
		cp "/tmp/selected-disko-config.nix" "$HOST_CONFIG_DIR/disko.nix" || _errormsg "Failed to copy /tmp/selected-disko-config.nix to $HOST_CONFIG_DIR"
	fi

	return 0
}

_install_nixos() {
	# /tmp will be cleared on bootup if nixos option boot.tmp.cleanOnBoot is set (which it is by default in my config)
	if [ "${LOW_RAM-}" ] && [ ! -e /mnt/tmp/swap ]; then
		# unless you are installing on a REALLY small drive, this will work fine
		SWAPFILE="/mnt/tmp/swap"
		printf "\nCreating a 4GB swap file at %s.\n" "$SWAPFILE"
		mkdir -p /mnt/tmp
		dd if=/dev/zero of="$SWAPFILE" bs=1024 count=4000000 || _errormsg "\nError: Unable to create swap file."
		mkswap "$SWAPFILE" || _errormsg "Could not use mkswap on $SWAPFILE"
		chmod 600 "$SWAPFILE" || _errormsg "Failed to change permissions for $SWAPFILE"
		swapon "$SWAPFILE" || _errormsg "Could not activate the swap file with swapon."
		printf "Success: This file will be cleared upon next bootup and Zram swap will be enabled to ensure your system runs smoothly after install.\n"
		unset SWAPFILE
	fi

	if [ -d "$CONFIG_ROOT/.git" ]; then
		# avoid the infamous bug with nix flakes where if the new files are not added to git, they cannot be realized to the /nix/store
		git -C "$CONFIG_ROOT" add "$CONFIG_ROOT" || _errormsg "git failed to add unstage files in $CONFIG_ROOT"
	fi

	printf "Installing NixOS\n"
	if [ ! -d "$HOST_CONFIG_DIR/users" ]; then
		# if no users have been configured, ensure root gets a password
		# This password will not be declaratively stored with sops.
		nixos-install --no-channel-copy --flake "$CONFIG_ROOT#$HOSTNAME" || _errormsg "\nERROR: Installation failed or aborted."
	else
		nixos-install --no-channel-copy --no-root-password --flake "$CONFIG_ROOT#$HOSTNAME" || _errormsg "\nERROR: Installation failed or aborted."
	fi

	y_or_n "Installation completed. Do you wish to reboot now?" && reboot
	exit 0
}

_select_disk() {
	while :; do
		SELECTED="$(
			# prevent unwriteable cdrom or loop devices from appearing
			for disk in $(lsblk -do name | grep -ve NAME -e 'sr' -e 'loop'); do
				DEVICE_PATH="/dev/$disk"
				printf "%s\n" "$DEVICE_PATH"
			done |
				fzf --border \
					--border-label-pos 1:top \
					--reverse \
					--border-label="Select a disk to install NixOS" \
					--preview='
						DISK_PATH={}
						printf "Associated Serials\n"
						printf "____________________\n\n"
						find /dev/disk/by-id -type l -not -path "*/nvme-eui*" | sed "s|\/dev\/disk\/by-id\/||" | while read -r serial; do
							[ "$(readlink -f "/dev/disk/by-id/$serial")" = "$DISK_PATH" ] && printf "%s\n" "$serial"
						done
						printf "\n\nBlock-Device contents\n"
						printf "____________________\n\n"
						lsblk -f "$DISK_PATH"
					' \
					--preview-window 'right,75%,border-left'
		)"

		if [ ! "${SELECTED-}" ]; then
			y_or_n "No disk was selected. Try again?" default="yes" && continue
			_errormsg "Aborted"
		else
			SELECTED_BLOCK_DEVICE="$SELECTED"
			unset SELECTED
			break
		fi
	done

	find /dev/disk/by-id ! -name "$(printf "*\n*")" -type l -not -path "*/nvme-eui*" >/tmp/discovered-disk-serials
	while IFS= read -r serial_path; do
		if [ "$(readlink -f "$serial_path")" = "$SELECTED_BLOCK_DEVICE" ]; then
			ASSOCIATED_DISK_SERIAL="$serial_path"
			break
		fi
	done </tmp/discovered-disk-serials
	rm /tmp/discovered-disk-serials || printf "Warning: failed to remove /tmp/discovered-disk-serials\n"

	if [ ! "${ASSOCIATED_DISK_SERIAL-}" ]; then
		printf "\nError: Could not find any serials for the selected disk: %s\n" "$SELECTED_BLOCK_DEVICE"
		printf "A hardware serial is required to ensure persistence across reinstallations of this host.\n"
		printf "This is likely an issue with some virtualization software like qemu/kvm.\n"
		printf "To continue, you will need to ensure the virtual disk is assigned a serial number in its configuration.\n"
		printf "Tip: If you are using virt-manager, navigate to your virtual disk -> Advanced options -> Serial, and enter any number.\n"
		return 1
	fi
}

_format_disks() {
	clear
	# edge case where it is unknown what is mounted so the user's input is required
	if [ "$(ls -A /mnt 2>/dev/null)" ]; then
		printf "\nFiles were found in the /mnt directory, which is where your system will be installed.\n"
		printf "This could be due to a mounted drive or a failed installation attempt.\n"
		printf "If this is due to a failed installation, you will not have to format the disks again.\n"
		printf "Otherwise, you should abort the installation and ensure that the disk is unmounted to prevent deletion of those files.\n"
		y_or_n "Do you wish to skip formatting?" default="yes" && return 0
	fi

	if [ "${INSTALLATION_METHOD}" = "existing" ]; then
		printf "\nBecause this is an existing configuration, you may wish to only repair the configuration or detect hardware changes.\n"
		printf "If this is the case, you should not continue with formatting because it will wipe any data on your disk.\n"
		y_or_n "Proceed with formatting" || return 0
	else
		printf "\nThe installer will use a nix-community tool, disko, to declaratively configure partitions for your hard drives or persistent storage volumes.\n"
		printf "By default, this will create a GPT partition table with a FAT32 partition for the bootloader and an ext4 partition for the OS root filesystem. This is suitable for most scenarios.\n"

		printf "\nIf you wish to deploy a custom setup, such as a dual boot, RAID, separate home partition, or the use of a different filesystem, add the nix file to %s before you continue.\n" "$DISKO_CONFIGURATIONS_DIR"
		printf "Note: These setups are very customizable and are for enthusists / advanced setups only, so these will not be included by default.\n"
		printf "For reference, the disko repository: https://github.com/nix-community/disko/example has several examples to help you get started.\n\n"

		y_or_n "Proceed with formatting?" default="yes" || _errormsg "Aborted"
	fi

	_validate_disko_file() {
		# will try its best detect whether the selected file is actually a disko file or is a bogus nix file
		# not 100% bullet-proof, but should be good enough.
		[ "${1-}" ] && [ -f "${1}" ] && grep -q "disko" "${1}"
	}

	if [ "${INSTALLATION_METHOD}" = "existing" ]; then
		if y_or_n "Reuse this host's disko file?" default="yes"; then
			EXISTING_DISKO_FILE="$REPO_DIR/nixosConfigurations/$HOSTNAME/disko.nix"
			if [ -f "$EXISTING_DISKO_FILE" ]; then
				SELECTED_DISKO_CONFIG="$EXISTING_DISKO_FILE"
			else
				printf "Warning: This host's disko file was not present in the expected location: %s.\n" "$EXISTING_DISKO_FILE"
				if y_or_n "Select a disko file from your repo instead?" default="yes"; then
					while :; do
						[ "${SELECTED-}" ] && unset SELECTED
						SELECTED="$REPO_DIR/$(find "$REPO_DIR" -type f -name "*.nix" | sed "s|$REPO_DIR\/||" | fzf)"
						if [ ! "${SELECTED-}" ]; then
							y_or_n "No file selected. Try again?" default="yes" || break
						else
							if _validate_disko_file "$SELECTED"; then
								SELECTED_DISKO_CONFIG="$SELECTED"
								break
							else
								if y_or_n "That disko file does not appear to be valid. Try again?" default="yes"; then
									continue
								else
									break
								fi
							fi
						fi
					done
					[ "${SELECTED-}" ] || y_or_n "Continue using the default disko configurations?" || _errormsg "Aborted"
				else
					y_or_n "Continue using the default disko configurations?" || _errormsg "Aborted"
				fi
			fi
		fi
		unset EXISTING_DISKO_FILE
	fi

	if [ ! "${SELECTED_DISKO_CONFIG-}" ]; then
		[ -d "${DISKO_CONFIGURATIONS_DIR}" ] || _errormsg "$DISKO_CONFIGURATIONS_DIR is not present on the filesystem."
		CUSTOM_DISKO_CONFIGURATIONS="$(find "$DISKO_CONFIGURATIONS_DIR" -type f | sed "s|$DISKO_CONFIGURATIONS_DIR\/||" | grep -v 'defaults')"
		if [ "${CUSTOM_DISKO_CONFIGURATIONS-}" ]; then
			while :; do
				if [ ! "${DONT_ASK-}" ]; then
					y_or_n "Custom configurations were found. Would you like to use one of them?" || break
				fi
				SELECTED="$(
					for config in $CUSTOM_DISKO_CONFIGURATIONS; do
						printf "%s\n" "$config"
					done | fzf \
						--disabled \
						--border \
						--border-label-pos 1:bottom \
						--preview="bat -f $DISKO_CONFIGURATIONS_DIR/{}" \
						--border-label='Found the following custom configurations.'
				)"
				if [ ! "${SELECTED-}" ]; then
					DONT_ASK=1
					y_or_n "No file selected, Try again?" default="yes" && continue
					_errormsg "Aborted"
				fi
				SELECTED_DISKO_CONFIG="$DISKO_CONFIGURATIONS_DIR/$SELECTED"
				unset CUSTOM_DISKO_CONFIGURATIONS SELECTED DONT_ASK
				break
			done
		fi

		# select an appropriate config from the defaults
		if [ ! "${SELECTED_DISKO_CONFIG-}" ]; then
			[ -z "$(ls -A "$DISKO_CONFIGURATIONS_DIR/defaults")" ] && _errormsg "default disko configurations were not found in $DISKO_CONFIGURATIONS_DIR"
			while :; do
				if _select_disk; then
					break
				else
					y_or_n "Errors were found with the previous selection. Select another disk?" || _errormsg "Aborted"
				fi
			done

			clear
			printf "\nOPTIONAL: To protect your persistent storage volume from theft, you can use the Linux Unified Key Setup (LUKS) to encrypt it.\n"
			printf "To do this, you will set up a passphrase that you will have to enter during your system boot.\n"

			printf "\nYour password should:\n"
			printf "1. Be different than any passwords used for other websites or services.\n"
			printf "2. Be easy to remember. If you lose this password, you will never be able to recover your files.\n"
			printf "3. Avoid using common dictionary words.\n"
			printf "4. NOT contain ANY public personal information: your birthday, grandpa's name, etc.\n"
			printf "5. NEVER be written down or stored anywhere except your memory.\n"
			printf "6. Be moderately long, the longer the more secure. (Recommend: roughly 16-30 characters).\n\n"

			if y_or_n "Would you like to set up LUKS encryption?" default="yes"; then
				while :; do
					PASSWORD="$(_enter_secret "Password: ")"
					if [ ! "${PASSWORD-}" ]; then
						printf "No password was entered. Try again.\n"
					else
						printf "\n"
						PASSWORD2="$(_enter_secret "Confirm Password: ")"
						[ "${PASSWORD}" = "${PASSWORD2-}" ] && break
						printf "\nPasswords do not match! Try again.\n"
					fi
				done
				printf "\n"
				printf "%s\n" "$PASSWORD" >/tmp/luks-password
				unset PASSWORD PASSWORD2
			fi

			[ -e "/tmp/luks-password" ] && SELECTED_DISKO_CONFIG="$DISKO_CONFIGURATIONS_DIR/defaults/gpt-ext4-luks.nix"
			SELECTED_DISKO_CONFIG="${SELECTED_DISKO_CONFIG:-"$DISKO_CONFIGURATIONS_DIR/defaults/gpt-ext4.nix"}"
		fi
	fi

	[ "${SELECTED_DISKO_CONFIG-}" ] || _errormsg "Disko configuration is still empty."
	cp -f "$SELECTED_DISKO_CONFIG" /tmp/selected-disko-config.nix

	# replace the /dev/sda in the template with the full path of the associated serial for the chosen disk.
	sed -i "s|device = \"\/dev\/sda\"|device = \"$ASSOCIATED_DISK_SERIAL\"|" "/tmp/selected-disko-config.nix"

	# remove any file already in /mnt
	printf "\nPreparing disko...\n"
	find /mnt -not -path '/mnt' -delete
	disko --mode destroy,format,mount "/tmp/selected-disko-config.nix" || DISKO_ERROR=1

	unset SELECTED_DISKO_CONFIG SELECTED_BLOCK_DEVICE
	if [ -e /tmp/luks-password ]; then
		rm /tmp/luks-password || printf "Warning: Failed to remove the luks password file /tmp/luks-password!\n"
	fi
	[ "${DISKO_ERROR-}" ] && _errormsg "Disko encountered an error while formatting drive!"
}

_install_existing() {
	while [ ! "${HOSTNAME-}" ]; do
		CONFIGURATIONS=$(nix eval "$REPO_DIR#nixosConfigurations" --apply builtins.attrNames | tr -d '"[]')
		HOSTNAME="$(for config in $CONFIGURATIONS; do
			printf "%s\n" "$config"
		done | fzf \
			--border \
			--border-label-pos 1:bottom \
			--border-label="Found the following configurations. Which would you like to install?")"
		if [ ! "${HOSTNAME-}" ]; then
			printf "\nNo host was selected\n"
			y_or_n "Would you like to try the selection again?" default="yes" || _errormsg "Aborted"
		fi
	done
	unset CONFIGURATIONS

	_format_disks

  if [ -e "$CONFIG_ROOT" ]; then
		rm -rf "$CONFIG_ROOT"
	fi
	mkdir -p "$CONFIG_ROOT"

	HOST_CONFIG_DIR="$CONFIG_ROOT/nixosConfigurations/$HOSTNAME"
	HOSTS_CONFIG_FILE="$CONFIG_ROOT/nixosConfigurations/default.nix"

	cp -rf "$REPO_DIR"/* "$CONFIG_ROOT" || _errormsg "Failed to copy contents of $REPO_DIR to $CONFIG_ROOT"
	_get_nixos_hardware_config

  # modify the arguments to the mkNixosHost function to reflect the host's current hardware state
	# Also needed to update system.stateVersion
	_get_hardware_info

	_set_hardware_parameter() {
		KEY_NAME="$1"
		KEY_VAL="$2"
		sed -i -r "/$HOSTNAME = slib.mkNixosHost/,/$KEY_NAME/ s|$KEY_NAME.*|$KEY_NAME = $KEY_VAL;|" "$HOSTS_CONFIG_FILE"
	}

  _set_hardware_parameter "firmware" "\"$FIRMWARE\""
	_set_hardware_parameter "cpu-vendor" "\"$CPU_VENDOR\""
	IFS=' '
	_set_hardware_parameter "gpu-vendors" "[ $(for vendor in $GPU_VENDORS; do
		printf "\"%s\"" "$vendor" 
  done) ]"
	unset IFS

  _set_hardware_parameter "isVM" "$IS_VM"
	_set_hardware_parameter "stateVersion" "\"$NIXOS_VERSION\""

	printf "\nchecking configuration\n"
  if [ "$(nix eval /mnt/etc/nixos'#'nixosConfigurations."$HOSTNAME".config.sops.secrets)" != "{ }" ]; then
		SOPS_PRIVATE_KEY_FILE="$(nix eval /mnt/etc/nixos'#'nixosConfigurations."$HOSTNAME".config.sops.age.keyFile | tr -d '"')"
		if [ ! -e "/mnt$SOPS_PRIVATE_KEY_FILE" ]; then
			printf "\nDetected sops secrets from this configuration.\n"
			printf "You will need to imperatively place your private age keys at /mnt%s before you continue\n" "$SOPS_PRIVATE_KEY_FILE"
			_confirm "Press any key to continue..."
		fi

		while [ ! -e "/mnt$SOPS_PRIVATE_KEY_FILE" ]; do
			printf "Keyfile not found.\nEnsure the file is present in /mnt%s before you continue.\n" "$SOPS_PRIVATE_KEY_FILE"
			_confirm "Press any key to continue..."
		done
	fi

	printf "\nChecks complete. No further action needed.\n"
	_install_nixos
}

_print_gpu_vendors() {
	if [ "${GPU_VENDORS-}" ]; then
		IFS=' '
		for vendor in $GPU_VENDORS; do
			printf "%s\n" "$vendor"
		done
		unset IFS
	fi
}

_set_hardware_info() {
	[ -d /sys/firmware/efi ] && FIRMWARE="UEFI"
	FIRMWARE="${FIMWARE:-"BIOS"}"

	if lscpu | grep -i "intel" >/dev/null; then
		CPU_VENDOR="intel"
	elif lscpu | grep -i "amd" >/dev/null; then
		CPU_VENDOR="amd"
	fi
	CPU_VENDOR="${CPU_VENDOR:-"other"}"

	lscpu | grep 'Hypervisor vendor:' >/dev/null && IS_VM="true"
	IS_VM="${IS_VM:-"false"}"

	_check_gpu_vendor() {
		if lspci -nn | grep "VGA" | grep -i "$1" >/dev/null; then
			if [ ! "${GPU_VENDORS-}" ]; then
				GPU_VENDORS="$1"
			else
				GPU_VENDORS="$GPU_VENDORS ""$1"
			fi
		fi
	}
	_check_gpu_vendor "nvidia"
	_check_gpu_vendor "amd"
	_check_gpu_vendor "intel"

	CPU_ARCH="$(uname -m)"
	NIXOS_VERSION=$(nixos-version | cut -d. -f1-2)
}

_sigint_cleanup() {
	stty "${DEFAULT_TTY_SETTINGS}"
	[ -e /tmp/luks-password ] && rm /tmp/luks-password
	[ -e /tmp/verify-ssh ] && rm /tmp/verify-ssh
	printf "\nInterrupted" >"$(tty)"
	exit 1
}

# main
DEFAULT_TTY_SETTINGS="$(stty -g)"
trap '_sigint_cleanup' INT

# tweakable global variables
DISKO_CONFIGURATIONS_DIR=${DISKO_CONFIGURATIONS_DIR:-"/etc/disko"}
# directory which will be scanned for existing hosts
REPO_DIR=${REPO_DIR:-"/tmp/your-globe"}
SUPPORTED_DESKTOP_ENVIRONMENTS="KDE|Niri|LabWC|Hyprland|None"
SUPPORTED_WEB_BROWSERS="Chromium|Helium|Firefox|Librewolf|Tor-Browser"

printf "\nYou are ready to begin installation.\n"

printf "\nFor questions in yes / no format, Typing 'y' or 'n' will answer them accordingly.\n"
printf "If a letter within [ ] at the end of the prompt is capitalized, pressing the return/enter key will use that answer by default.\n"
printf "As a general rule of thumb, If you are unsure what a question is asking, press the enter key to select the provided default.\n\n"

_confirm "Press any key to continue..."

printf "\nIf you have used this installer before, You might have already configured a fleet of NixOS machines.\n"
printf "With access to your remote git provider, you can re-install a previously configured host or seamlessly integrate this machine into your fleet.\n"
if y_or_n "Do you wish to use a git repository that was derived from this installer?" default="no"; then
	_clone_repo
	while :; do
		printf "\n"
		printf "1. Install/Repair this host with an existing configuration.\n"
		printf "2. Integrate this new host with your fleet.\n"
		printf "3. Abort.\n"
		printf "Your selection: "
		read -r SELECTED
		SELECTED="$(printf "%s" "$SELECTED" | tr -dc '[:digit:]')"
		if [ ! "${SELECTED-}" ] || [ "${SELECTED}" -gt 3 ]; then
			printf "Invalid selection. Try again.\n"
			continue
		else
			break
		fi
	done

	case "$SELECTED" in
	"1") INSTALLATION_METHOD="existing" ;;
	"2") INSTALLATION_METHOD="integrate" ;;
	*) _errormsg "Aborted" ;;
	esac
fi

INSTALLATION_METHOD="${INSTALLATION_METHOD:-"new"}"
[ "$INSTALLATION_METHOD" = "existing" ] && _install_existing

_format_disks

CONFIG_ROOT="/mnt/etc/nixos"
HOSTS_CONFIG_FILE="$CONFIG_ROOT/nixosConfigurations/default.nix"
DEFAULT_MODULES_DIR="$CONFIG_ROOT/nixosModules/default"
KEYRING_FILE="$DEFAULT_MODULES_DIR/keyring.nix"

if [ -d "${CONFIG_ROOT}" ]; then
	rm -rf "$CONFIG_ROOT" || _errormsg "Failed to remove $CONFIG_ROOT"
fi

mkdir -p "$CONFIG_ROOT" || _errormsg "Failed to create $CONFIG_ROOT"
if [ "${REPO_DIR-}" ] && [ "${INSTALLATION_METHOD}" = "integrate" ]; then
	cp -rf "$REPO_DIR"/* "$CONFIG_ROOT" || _errormsg "Failed to copy contents of $REPO_DIR to $CONFIG_ROOT"
fi

_set_hostname() {
	printf "Warning: Hostname will be cleansed of characters that are not [a-z][A-Z][0-9], -, or _\n"
	while :; do
		printf "Hostname: "
		read -r HOSTNAME
		HOSTNAME="$(printf "%s" "$HOSTNAME" | tr -dc '[:digit:][:upper:][:lower:]-_')"
		if [ "${HOSTNAME-}" ]; then
			HOST_CONFIG_DIR="$CONFIG_ROOT/nixosConfigurations/$HOSTNAME"
			if [ -d "$HOST_CONFIG_DIR" ]; then
				printf "A host with that name already exists in your fleet. Enter another hostname.\n"
				continue
			else
				break
			fi
		fi
		printf "Hostname cannot be empty!\n"
	done
	HOST_CONFIG_FILE="$HOST_CONFIG_DIR/configuration.nix"
}

_set_timezone() {
	if y_or_n "Set a static time zone?" default="no"; then
		while :; do
			TIMEZONE=$(timedatectl list-timezones | fzf \
				--border \
				--border-label-pos 1:bottom \
				--border-label="Select time zone")
			if [ ! "${TIMEZONE-}" ]; then
				y_or_n "No time zone selected. Try again?" default="yes" && continue
				printf "A static time zone will not be set.\n"
			fi
			break
		done
	fi
}

_set_locale() {
	[ "${LOCALE-}" ] && unset LOCALE
	y_or_n "Use the default localization configuration? (en_US.UTF-8)" default="yes" && LOCALE="en_US.UTF-8"
	if [ ! "${LOCALE-}" ]; then
		while :; do
			LOCALE=$(cat /etc/locales.txt | fzf \
				--border \
				--border-label-pos 1:bottom \
				--border-label="Select the default locale")
			if [ ! "${LOCALE-}" ]; then
				y_or_n "No locale selected. Try again?" default="yes" && continue
				printf "Assuming default locale: en_US.UTF-8\n"
				LOCALE="en_US.UTF-8"
			else
				LOCALE="$LOCALE"".UTF-8"
			fi
			break
		done
	fi
}

_set_xkb_layout() {
	unset XKB_LAYOUT
	y_or_n "Use the default keyboard layout? (US)" default="yes" && XKB_LAYOUT="us"
	if [ ! "${XKB_LAYOUT-}" ]; then
		XKB_LAYOUT=$(localectl list-keymaps | fzf \
			--border \
			--border-label-pos 1:bottom \
			--border-label="Select a keyboard layout")
		if [ ! "${XKB_LAYOUT-}" ]; then
			printf "\nNo layout selected, assuming default (US)\n"
			XKB_LAYOUT="us"
		fi
	fi
}

_enable_profile() {
	if [ ! "${OPTIONAL_PROFILES-}" ]; then
		OPTIONAL_PROFILES="$1"
	else
		OPTIONAL_PROFILES="$OPTIONAL_PROFILES ""$1"
	fi
}

_set_optional_profiles() {
	[ "${OPTIONAL_PROFILES-}" ] && unset OPTIONAL_PROFILES
	y_or_n "Install programs for hardware diagnostics?" default="no" && _enable_profile "hardware-tools"
	if [ "${DESKTOP_ENVIRONMENT-}" ]; then
		y_or_n "Install programs for gaming? (steam, lutris, etc?)" default="no" && _enable_profile "gaming"
		y_or_n "Install programs for office work? (libreoffice, email client, local CUPS printing server, etc?)" default="no" && _enable_profile "office"
	fi
	y_or_n "Install penetration and security testing tools from Kali Linux? (nmap, tor-browser, john-the-ripper, wireshark, etc)" default="no" && _enable_profile "hacker-mode"
	y_or_n "Install additional nix tools? (recommended for developers)" default="no" && _enable_profile "nix-tools"
	y_or_n "Would you like to harden your configuration? This disables some features like password-based ssh authentication and mutable user configuration for increased security." default="no" && _enable_profile "harden"
}

_set_desktop_environment() {
	[ "${DESKTOP_ENVIRONMENT-}" ] && unset DESKTOP_ENVIRONMENT

	KDE_DESCRIPTION="A modern all inclusive desktop environment.
Very similar to Microsoft Windows 11.
Perfect for beginners."

	LABWC_DESCRIPTION="A very simple and lightweight DIY wayland compositor
that uses a stacking window layout."

	HYPRLAND_DESCRIPTION="A high-quality, modern DIY wayland window manager.
Uses a traditional dynamic tiling layout
with an emphasis on visual appearance."

	NIRI_DESCRIPTION="A high-quality, modern DIY wayland window manager.
Uses infinite scrolling windows in a tiled format."

	while :; do
		DESKTOP_ENVIRONMENT="$(
			IFS='|'
			for desktop in $SUPPORTED_DESKTOP_ENVIRONMENTS; do
				printf "%s\n" "$desktop"
			done | fzf \
				--disabled \
				--border \
				--reverse \
				--border-label-pos 1:top \
				--border-label='Select a desktop environment' \
				--preview-window 'right,75%,border-left' \
				--preview "
			case {} in
				'KDE') printf '$KDE_DESCRIPTION' ;;
				'Niri') printf '$NIRI_DESCRIPTION' ;;
				'LabWC') printf '$LABWC_DESCRIPTION' ;;
				'Hyprland') printf '$HYPRLAND_DESCRIPTION' ;;
				*) printf 'No desktop environment will be installed' ;;
			esac" | tr '[:upper:]' '[:lower:]'
		)"
		if [ ! "${DESKTOP_ENVIRONMENT-}" ]; then
			y_or_n "No desktop selected. Would you like to try again?" default="yes" && continue
			printf "No desktop environment will be installed\n"
		fi
		break
	done
	if [ "${DESKTOP_ENVIRONMENT}" = "none" ]; then
		printf "No desktop environment will be installed\n"
		unset DESKTOP_ENVIRONMENT
	fi
	unset IFS NIRI_DESCRIPTION HYPRLAND_DESCRIPTION KDE_DESCRIPTION LABWC_DESCRIPTION
}

clear
printf "Note: For the next steps, if you happen to enter information incorrectly, you can change it later.\n"

printf "\nfirst, set your system's host name.\n"
printf "This name will be used by networks to identify your machine.\n"
printf "Ex: Bobs-Laptop\n"
_set_hostname

printf "\nNow you will need to configure the time zone.\n"
printf "If you do not choose to set a static time zone, it will be configured automatically by your approximate geolocation.\n"
printf "The list contains all UNIX TZ identifiers.\n"
printf "If you need help with which one to select, you can use this tool: https://tz.jamie.holdings/\n"
_set_timezone

printf "\n"
_set_locale

printf "\n"
_set_xkb_layout

printf "\nWarning: The selected layout will only apply to window managers using the xserver and the Linux Virtual Console.\n"
printf "For Wayland compositors like Niri or Hyprland, you will have to set the keymap in their respective configuration files.\n\n"

_set_desktop_environment
_set_optional_profiles
_set_hardware_info

while :; do
	clear
	printf "Your host will be installed with the following configuration:\n"

	printf "\nDetected Hardware Configuration:\n"
	printf "CPU Brand - %s\n" "$CPU_VENDOR"
	if [ "${GPU_VENDORS-}" ]; then
		printf "GPU Brands - %s\n" "$(_print_gpu_vendors)"
	fi
	printf "Firmware - %s\n" "$FIRMWARE"
	printf "CPU Arch - %s\n" "$CPU_ARCH"

	printf "\nNixOS Information\n"
	printf "Version - %s\n" "$NIXOS_VERSION"

	printf "\nUser-selected preferences and system identifiers:\n"
	printf "Hostname - %s\n" "$HOSTNAME"
	printf "Locale - %s\n" "$LOCALE"
	printf "Keyboard Layout - %s\n" "$XKB_LAYOUT"
	if [ "${TIMEZONE-}" ]; then
		printf "Timezone - %s\n" "$TIMEZONE"
	else
		printf "Timezone - Dynamic by geolocation\n"
	fi
	if [ "${DESKTOP_ENVIRONMENT-}" ]; then
		printf "Desktop - %s\n" "$DESKTOP_ENVIRONMENT"
	else
		printf "Desktop - None\n"
	fi
	if [ "${OPTIONAL_PROFILES-}" ]; then
		for profile in $OPTIONAL_PROFILES; do
			printf "Optional Profile - %s\n" "$profile"
		done
	fi

	printf "\n"
	y_or_n "Are you satisfied with the current configuration?" default="yes" && break
	clear

	OPTIONS="Hostname|Desktop|Locale|Keyboard Layout|Timezone|Optional Profiles"
	IFS='|'
	SELECTED="$(
		for option in $OPTIONS; do
			printf "%s\n" "$option"
		done | fzf \
			--disabled \
			--border \
			--border-label-pos 1:bottom \
			--border-label="Which do you wish to change? (Press esc or Ctrl+C to continue)"
	)"
	unset IFS
	case "${SELECTED-}" in
	"Hostname") _set_hostname ;;
	"Desktop") _set_desktop_environment ;;
	"Locale") _set_locale ;;
	"Keyboard Layout") _set_xkb_layout ;;
	"Timezone") _set_timezone ;;
	"Optional Profiles") _set_optional_profiles ;;
	*) continue ;;
	esac
done

if [ "${INSTALLATION_METHOD}" = "new" ]; then
	# flake.nix
	printf "{
			description = \"my NixOS configurations\";

			inputs = {
				snowglobe-factory = {
					url = \"git+https://codeberg.org/earthgman/snowglobe-factory\";
					# Be sure to also uncomment this if you use your own nixpkgs input to avoid duplicate nixpkgs repos in the store.
					# inputs.nixpkgs.follows = \"nixpkgs\";
				};

				nixpkgs.follows = \"snowglobe-factory/nixpkgs\";
				# comment above and uncomment below to pin your own nixpkgs revision in the flake.lock.
				# Could cause instabilities, use at your own risk.
				# nixpkgs = {
				#   url = \"github:NixOS/nixpkgs/nixos-unstable\";
				# };

				import-tree.follows = \"snowglobe-factory/import-tree\";
			};

			outputs = { self, nixpkgs, snowglobe-factory, ... }:
			let
				flake = self;
				lib = nixpkgs.lib;
				inputs = flake.inputs;
				outputs = flake.outputs;
				import-tree = inputs.import-tree;

				# helper function for outputs that require an output for each system arch
				perSystem =
				let
					# add more systems as you need
					systems = [
						\"x86_64-linux\"
						\"aarch64-linux\"
					];
				in
				src:
				lib.genAttrs systems (
					system:
					import src {
						inherit flake;
						pkgs = import nixpkgs {
							inherit system;
							config.allowUnfree = true;
							overlays = builtins.attrValues outputs.overlays;
						};
					}
				);
			in
			{
				# expose hosts configured under this flake
				nixosConfigurations = import ./nixosConfigurations { inherit flake; };

				# expose your custom modules.
				nixosModules.default = import-tree [
					./nixosModules/default
					# transform set of your overlays to a list
					{ nixpkgs.overlays = builtins.attrValues outputs.overlays; }
				];

				# expose your package set modifications
				overlays = import ./overlays { inherit flake; };

				# expose your custom derivations
				packages = perSystem ./packages;
				# example devshell
				devShells = perSystem ./devshell.nix;
			};
		}" | install -D /dev/stdin "$CONFIG_ROOT/flake.nix"

	# nixosModules/default/default.nix
	printf "
		{
			pkgs,
			lib,
			config,
			...
		}:
		{
			# example for merging your shared config
			config = lib.mkMerge [
			# {
			#	  your-name-here.your-module-1.enable = true;
			#	  your-name-here.your-module-2.enable = true;
			#	  # more module boilerplate here
			#	  ...
			#	}
			
			#	You can also define and enable modules only if a certain condition is met
			#	(lib.mkIf (some condition here) {
			#	  your-name-here.module-3.enable = true;
			#	  # any other modules
			#	  ...
			# })
			];
	}" | install -D /dev/stdin "$DEFAULT_MODULES_DIR/default.nix"

	# devshell
	printf "
	{ pkgs, flake }:
	{
		default = pkgs.mkShell {
			packages = [ pkgs.cowsay ];
		};
	} " | install -D /dev/stdin "$CONFIG_ROOT/devshell.nix"

	# packages
	printf "
	  # create custom derivations using pkgs.callPackage
		{ pkgs, flake }:
		{
			# my-package = pkgs.callPackage ./my-package.nix { };
		}" | install -D /dev/stdin "$CONFIG_ROOT/packages/default.nix"

	# overlays
	printf "
		# overlays are functions which modify the existing nix package set used by your flake.
		# you can use them to add, remove, or modify packages.
		{ flake }:
		let
			inputs = flake.inputs;
		in
		{
			# make custom packages available to your nixos configurations from the 'pkgs' function argument
			my-packages = final: prev: import ../packages {
				inherit flake;
				pkgs = final;
			};

			# examples for installing rolling release of some popular projects.
			# of course, you will need to add the input to your flake for them to work.
			# ghostty-git = inputs.ghostty.overlays.default;
			# hyprland-git = inputs.hyprland.overlays.packages;
		}" | install -D /dev/stdin "$CONFIG_ROOT/overlays/default.nix"
fi
mkdir -p "$HOST_CONFIG_DIR"

if [ ! -e "$KEYRING_FILE" ]; then
	printf "# do not remove this file! It is used by the installer to manage and reference your keys
{
	keyring = {
		ssh = { };
		age = { };
		openpgp = { };
	};
}" | install -D /dev/stdin "$KEYRING_FILE"
fi

# sops setup
printf "\nBefore configuring your user accounts, you will need to configure sops-nix.\n"
printf "By default, all nix configuration files, including those containing hashed passwords or other secrets, will be world-readable in /nix/store.\n"
printf "To circumvent this security limitation of NixOS, you can use a sops-nix configuration to encrypt part of your configuration so it can be safely stored in public repositories.\n"
printf "While other key-based encryption formats can be used for sops-nix. The installer will use age.\n\n"
_confirm "Press any key to continue..."

[ -e "${KEYRING_FILE}" ] && HAS_KEYRING=1
PRIVATE_KEY_FILE="/mnt/root/.config/sops/age/keys.txt"
SOPS_YAML="$CONFIG_ROOT/.sops.yaml"
HOST_SECRETS_FILE="$HOST_CONFIG_DIR/secrets.yaml"
RELATIVE_HOST_SECRETS_FILE="nixosConfigurations/$HOSTNAME/secrets.yaml"

if [ -e "${PRIVATE_KEY_FILE-}" ]; then
	rm "$PRIVATE_KEY_FILE" || _errormsg "Failed to remove existing private key file: $PRIVATE_KEY_FILE"
fi
mkdir -p "/mnt/root/.config/sops/age"

_remove_key_dictionary() {
	rm -rf "$KEY_DICTIONARY_DIR" || _errormsg "Failed to clean up key dictionary: $KEY_DICTIONARY_DIR"
	unset KEY_DICTIONARY_DIR
}

_build_key_dictionary() {
	[ -d "${KEY_DICTIONARY_DIR-}" ] && _remove_key_dictionary
	# [ "${1-}" ] || _errormsg "_build_key_dictionary called with no arguments"
	[ "${1-}" ] && KEYVALUE_PAIRS="$1"
	KEY_DICTIONARY_DIR="$(mktemp -d || _errormsg "Failed to create key dictionary with mktemp")"
	if [ "${KEYVALUE_PAIRS-}" ]; then
		IFS=';'
		for key in $KEYVALUE_PAIRS; do
			KEY_NAME="$(printf "%s" "$key" | cut -d= -f1)"
			KEY_VALUE="$(printf "%s" "$key" | cut -d= -f2)"
			if [ ! "${KEY_NAME-}" ] || [ ! "${KEY_VALUE-}" ]; then
				_errormsg "Something about the keyring file from this repo is not correct. Ensure each key name matches one value."
			fi
			printf "%s\n" "$KEY_VALUE" >"$KEY_DICTIONARY_DIR/$KEY_NAME"
		done
		unset IFS
	fi
}

if [ "${HAS_KEYRING-}" ]; then
	AGE_KEY_PAIRS=$(nix eval --file "$KEYRING_FILE" keyring.age | tr -d '{ }')
	if [ "${AGE_KEY_PAIRS-}" ]; then
		_build_key_dictionary "$AGE_KEY_PAIRS"
		if y_or_n "Found configured age keys on your keyring. Would you like to use one of those?"; then
			while :; do
				AGE_KEY_NAME="$(
					for key in "$KEY_DICTIONARY_DIR"/*; do
						printf "%s\n" "$(basename "$key")"
					done | fzf \
						--border \
						--border-label-pos 1:bottom \
						--border-label="Found the following age keys on your keyring. (Ctrl+C or esc to cancel)"
				)"
				if [ "${AGE_KEY_NAME-}" ]; then
					AGE_PUBLIC_KEY="$(cat "$KEY_DICTIONARY_DIR/$AGE_KEY_NAME")"
					break
				else
					y_or_n "No key selected. Try again?" default="yes" || break
				fi
			done
		fi
		_remove_key_dictionary
	fi
fi

if [ ! "${AGE_KEY_NAME-}" ]; then
	printf "\nGenerating age key pair...\n"
	age-keygen -o "$PRIVATE_KEY_FILE" >/dev/null || _errormsg "Failed to generate age key pair.\n"
	AGE_PUBLIC_KEY=$(cat "$PRIVATE_KEY_FILE" | grep "public key:" | cut -d ":" -f2 | tr -d " ")

	while :; do
		printf "Warning: Key name will be cleansed of characters that are not [a-z][A-Z][0-9], -, or _\n"
		printf "\nCreate an alias for your key (\`default\`, \`workstations\`, \`homelab\`, etc): "
		read -r AGE_KEY_NAME
		AGE_KEY_NAME=$(printf "%s" "$AGE_KEY_NAME" | tr -dc '[:digit:][:upper:][:lower:]-_')

		if [ ! "${AGE_KEY_NAME-}" ]; then
			printf "Key name cannot be empty!\n"
			continue
		fi

		if [ -e "$CONFIG_ROOT/.sops.yaml" ]; then
			if cat "$CONFIG_ROOT/.sops.yaml" | grep "\- &$AGE_KEY_NAME" >/dev/null; then
				printf "\nWarning: Detected duplicate key names/aliases in .sops.yaml. Your new key must have a different name than any of your other keys. Try again.\n"
			else
				break
			fi
		else
			break
		fi
	done
	# write newly generated key to the keyring
	sed -i "s|\(age = {\)\([^}]*\)|\1\n\t$AGE_KEY_NAME = \"$AGE_PUBLIC_KEY\";\n|" "$KEYRING_FILE"

	clear
	printf "IMPORTANT:\n"
	printf "The generated private key is stored at %s.\n" "$PRIVATE_KEY_FILE"
	printf "This will allow the super user (sudo) to create and modify your secrets for this host.\n"
	printf "It is imperative that you create a backup of this private key after installation is complete. If you lose it, you will no longer be able to access your secrets and your system cannot rebuild.\n"
	_confirm "Press any key to acknowledge..."
	NEW_AGE_KEY=1
# else if the key was selected from your keyring
else
	while :; do
		printf "Selected key name: %s\n" "$AGE_KEY_NAME"
		printf "Selected public key: %s\n" "$AGE_PUBLIC_KEY"
		printf "You will have to place the corresponding private key file at the following location: %s\n" "$PRIVATE_KEY_FILE"
		printf "The file must be in proper age format or else the install will fail.\n"
		printf "Tip: you can use 'scp' to securely send the private key to this machine over ssh.\n"
		_confirm "Press any key once the file is in place..."

		if [ -f "$PRIVATE_KEY_FILE" ]; then
			break
		else
			y_or_n "The private key file was not found. Try again?" default="yes" || _errormsg "Aborted"
		fi
	done
fi

# assume that if the key is on the keyring then it is already in .sops.yaml
if [ -e "$CONFIG_ROOT/.sops.yaml" ]; then
	if [ "${NEW_AGE_KEY-}" ]; then
		sed -i "/keys:/a\  - &$AGE_KEY_NAME $AGE_PUBLIC_KEY" $CONFIG_ROOT/.sops.yaml
	fi
	sed -i "/creation_rules:/a\  - path_regex: $HOST_SECRETS_FILE\n    key_groups:\n      - age:\n          - *$AGE_KEY_NAME" "$SOPS_YAML"
else
	# sops yaml doesn't exist so create it
	printf "keys:
  - &%s %s
creation_rules:
  - path_regex: %s
    key_groups:
      - age:
          - *%s" "$AGE_KEY_NAME" "$AGE_PUBLIC_KEY" "$RELATIVE_HOST_SECRETS_FILE" "$AGE_KEY_NAME" >"$SOPS_YAML"
fi

# ensure secure permissions are set for the private key
chmod 600 "$PRIVATE_KEY_FILE" || _errormsg "Failed to set permissions for the age private key $PRIVATE_KEY_FILE"

# write this host's configuration files
printf '{ pkgs, lib, config, ... }:
	{
		i18n.defaultLocale = "%s";
		services.xserver.xkb.layout = "%s";
' \
	"$LOCALE" "$XKB_LAYOUT" >"$HOST_CONFIG_FILE"

[ "${TIMEZONE-}" ] && printf "time.timeZone = \"%s\";\n" "$TIMEZONE" >>"$HOST_CONFIG_FILE"
[ "${DESKTOP_ENVIRONMENT-}" ] && printf "snowglobe-factory.desktop.%s.enable = true;\n" "$DESKTOP_ENVIRONMENT" >>"$HOST_CONFIG_FILE"

if [ "${OPTIONAL_PROFILES-}" ]; then
	printf "\n# custom profiles\n" >>"$HOST_CONFIG_FILE"
	IFS=' '
	for profile in $OPTIONAL_PROFILES; do
		printf "snowglobe-factory.profiles.%s.enable = true;\n" "$profile" >>"$HOST_CONFIG_FILE"
	done
	unset IFS
fi

# disable the provided cache
if [ "${CACHE_UNTRUSTED-}" ]; then
	printf "\n# Don't trust the provided cache\n" >>"$HOST_CONFIG_FILE"
	printf "substituters.\"nix-store.earthgman.dev\".enable = false;\n" >>"$HOST_CONFIG_FILE"
fi
printf "}" >>"$HOST_CONFIG_FILE"

# add this new host to the hosts file
if [ "${INSTALLATION_METHOD}" = "integrate" ]; then
	# remove the last character to make way for the new configuration
	sed -i '$ s/.$//' "$HOSTS_CONFIG_FILE"
else
	# add the function header if this is a new configuration
	printf "{ flake }:
let
	inputs = flake.inputs;
	outputs = flake.outputs;
	lib = inputs.nixpkgs.lib;
	slib = inputs.snowglobe-factory.lib;
in
	{\n" >"$HOSTS_CONFIG_FILE"
fi

printf '	%s = slib.mkNixosHost {
		hostname = "%s";
		cpu-vendor = "%s";
		gpu-vendors = [ %s ];
		firmware = "%s";
		isVM = %s;
		configDir = ./%s;
		specialArgs = { inherit flake; };
		modules = [ outputs.nixosModules.default ];
		stateVersion = "%s";
	};
}' \
	"$HOSTNAME" \
	"$HOSTNAME" \
	"$CPU_VENDOR" \
	"$(_print_gpu_vendors)" \
	"$FIRMWARE" \
	"$IS_VM" \
	"$HOSTNAME" \
	"$NIXOS_VERSION" >>"$HOSTS_CONFIG_FILE"

# generate hardware-configuration.nix and move disko.nix into place
_get_nixos_hardware_config

# user creation
clear
printf "\nNow you must add and configure user accounts.\n"
printf "By default, the root user will not be accessible unless configured in this section.\n"
printf "So if you wish to add a method of authentication for root, simply type \`root\` for username.\n"
printf "Otherwise, a user with the provided username will be created.\n"
printf "Similar to the base system configuration, you will be asked if you want to correct any mistakes you made.\n\n"

_set_username() {
	[ "${USERNAME-}" ] && unset USERNAME
	printf "Warning: Username will be cleansed of characters that are not [a-z][A-Z][0-9], -, or _\n"
	while :; do
		printf "Username: "
		read -r USERNAME
		USERNAME="$(printf "%s" "$USERNAME" | tr -dc '[:digit:][:upper:][:lower:]-_')"
		if [ ! "${USERNAME-}" ]; then
			printf "Username cannot be empty.\n"
			continue
		else
			if [ "${USERS-}" ]; then
				for user in $USERS; do
					if [ "$user" = "$USERNAME" ]; then
						printf "\nWarning: A user with that username has already been configured. Enter another username.\n"
						continue
					fi
				done
			fi
			break
		fi
	done
	if [ "${USERNAME}" = "root" ]; then
		IS_ROOT=1
	else
		[ "${IS_ROOT}" ] && unset IS_ROOT
	fi

}

_set_password() {
	while :; do
		PASSWORD="$(_enter_secret "Enter Password: ")"
		printf "\n"
		if [ ! "${PASSWORD-}" ]; then
			y_or_n "No password provided. Try Again?" default="yes" && continue
			break
		fi
		PASSWORD2="$(_enter_secret "Confirm Password: ")"
		printf "\n"
		if [ "${PASSWORD}" != "${PASSWORD2-}" ]; then
			printf "\nPassword do not match! Try again.\n"
			continue
		else
			break
		fi
	done
	unset PASSWORD2
}

_add_ssh_key() {
	[ "${1-}" ] || _errormsg "_add_ssh_key called without any arguments."
	if [ ! "${AUTHORIZED_SSH_KEYS-}" ]; then
		AUTHORIZED_SSH_KEYS="$1"
	else
		AUTHORIZED_SSH_KEYS="$AUTHORIZED_SSH_KEYS ""$1"
	fi
}

_configure_ssh_keys() {
	[ "${AUTHORIZED_SSH_KEYS-}" ] && unset AUTHORIZED_SSH_KEYS
	if [ "${HAS_KEYRING-}" ]; then
		SSH_KEY_PAIRS="$(nix eval --file "$KEYRING_FILE" keyring.ssh | tr -d '{  }')"
	fi
	if [ "${SSH_KEY_PAIRS-}" ]; then
		_build_key_dictionary "$SSH_KEY_PAIRS"
		if y_or_n "Found configured ssh keys on your keyring. Would you like to use one of those?"; then
			SSH_KEY_NAMES="$(ls -A "$KEY_DICTIONARY_DIR")"
			while :; do
				SSH_KEY_NAME="$(
					for key in $SSH_KEY_NAMES; do
						printf "%s\n" "$key"
					done | fzf \
						--border \
						--border-label-pos 1:bottom \
						--border-label="Found the following SSH keys on your keyring. Use one of these? (Ctrl+C or esc to cancel)"
				)"
				if [ ! "${SSH_KEY_NAME}" ]; then
					y_or_n "No key was selected. Try again?" default="yes" || break
				else
					_add_ssh_key "$SSH_KEY_NAME"
					for keyname in $SSH_KEY_NAMES; do
						if [ "$keyname" != "$SSH_KEY_NAME" ]; then
							if [ ! "${TMP-}" ]; then
								TMP="$keyname"
							else
								TMP="$TMP ""$keyname"
							fi
						fi
					done
					SSH_KEY_NAMES="$TMP"
					unset TMP

					if [ ! "${SSH_KEY_NAMES-}" ]; then
						break
					else
						y_or_n "Add another key from your keyring?" || break
					fi
				fi
			done
		fi
	fi

	if [ "${AUTHORIZED_SSH_KEYS}" ]; then
		y_or_n "Add any additional keys not present on your keyring?" default="no" || return 0
	fi

	[ ! "${KEY_DICTIONARY_DIR}" ] && _build_key_dictionary
	while :; do
		while :; do
			printf "Enter a valid ssh public key: "
			read -r SSH_PUBLIC_KEY
			if [ ! "${SSH_PUBLIC_KEY-}" ]; then
				y_or_n "No key was entered. Try again" || return 1
			else
				printf "%s\n" "$SSH_PUBLIC_KEY" >/tmp/verify-ssh || _errormsg "Failed to write key value /tmp/verify-ssh"
				if ! ssh-keygen -l -f /tmp/verify-ssh >/dev/null 2>&1; then
					y_or_n "That ssh does not seem valid. Try again?" || return 1
				else
					break
				fi
			fi
		done

		KEY_NAMES="$(ls -A "$KEY_DICTIONARY_DIR")"
		while :; do
			printf "Warning: key name will be stripped of numbers and special characters except for '-' and '_'\n"
			printf "Give a name to this key for your keyring: "
			read -r SSH_KEY_NAME
			SSH_KEY_NAME="$(printf "%s" "$SSH_KEY_NAME" | tr -dc '[:upper:][:lower:]-_')"
			if [ ! "${SSH_KEY_NAME-}" ]; then
				printf "Key name cannot be empty. Try again.\n"
				continue
			else
				if [ "${KEY_NAMES-}" ]; then
					for keyname in $KEY_NAMES; do
						if [ "${SSH_KEY_NAME}" = "$keyname" ]; then
							DUPLICATE_DETECTED=1
							break
						fi
					done
					if [ "${DUPLICATE_DETECTED-}" ]; then
						unset DUPLICATE_DETECTED
						printf "A key with the provided name is already present on your keyring. Try again.\n"
						continue
					fi
				fi
			fi
			printf "Key name: %s\n" "$SSH_KEY_NAME"
			break
		done

		_add_ssh_key "$SSH_KEY_NAME"
		sed -i "s|\(ssh = {\)\([^}]*\)|\1\n\t$SSH_KEY_NAME = \"$SSH_PUBLIC_KEY\";|" "$KEYRING_FILE"
		printf "%s\n" "$SSH_PUBLIC_KEY" >"$KEY_DICTIONARY_DIR/$SSH_KEY_NAME"
		y_or_n "Authorize another ssh key?" || break
	done

	_remove_key_dictionary
}

_select_browser() {
	FIREFOX_DESCRIPTION="Default firefox configuration from mozilla."
	LIBREWOLF_DESCRIPTION="debloated Mozilla Firefox configuration with an emphasis on
privacy and security."
	CHROMIUM_DESCRIPTION="open source alternative to google-chrome."
	HELIUM_DESCRIPTION="Debloated chromium based browser designed with 
simplicity and security in mind."
	TOR_BROWSER_DESCRIPTION="Firefox based browser officially supported by the tor project
for use of The Onion Router protocol (TOR)"

	IFS='|'
	while :; do
		SELECTED="$(
			for browser in $SUPPORTED_WEB_BROWSERS; do
				printf "%s\n" "$browser"
			done | fzf \
				--disabled \
				--border \
				--border-label-pos 1:bottom \
				--border-label="Pick your favorite web browser" \
				--preview="
					case {} in
					'Firefox') printf '$FIREFOX_DESCRIPTION'
					'Librewolf') printf '$LIBREWOLF_DESCRIPTION'
					'Chromium') printf '$CHROMIUM_DESCRIPTION'
					'Helium') printf '$HELIUM_DESCRIPTION'
					'Tor-Browser') printf '$TOR_BROWSER_DESCRIPTION'
					esac
				" | tr '[:upper:]' '[:lower:]'
		)"

		if [ ! "${SELECTED-}" ]; then
			y_or_n "No browser selected. Try again?" default="yes" || break
		else
			case "$SELECTED" in
			"chromium") WEB_BROWSER="chromium-browser" ;;
			*) WEB_BROWSER="$SELECTED" ;;
			esac
			break
		fi
	done

	unset IFS SELECTED FIREFOX_DESCRIPTION LIBREWOLF_DESCRIPTION CHROMIUM_DESCRIPTION HELIUM_DESCRIPTION TOR_BROWSER_DESCRIPTION
}

_set_permission() {
	[ "${1-}" ] || _errormsg "_set_permission called without any arguments."
	if [ ! "${USER_PERMISSIONS-}" ]; then
		USER_PERMISSIONS="$1"
	else
		USER_PERMISSIONS="$USER_PERMISSIONS ""$1"
	fi
}

_set_permissions() {
	[ "${USER_PERMISSIONS-}" ] && unset USER_PERMISSIONS
	y_or_n "Should this user have access to privilege escalation? (ability to run as sudo)" default="yes" && _set_permission "wheel"
	if [ "${DESKTOP_ENVIRONMENT-}" ]; then
		y_or_n "Should this user be allowed to add, remove, and manage network connections with networkmanager?" default="yes" && _set_permission "networkmanager"
	fi
}

_add_user() {
	if [ ! "${USERS-}" ]; then
		USERS="$1"
	else
		USERS="$USERS ""$1"
	fi
}

# user creation loop
while :; do
	_set_username
	y_or_n "Set a password for this user?" default="yes" && _set_password
	y_or_n "Add an ssh key for authentication with this user over openssh?" default="no" && _configure_ssh_keys
	# set permissions for normal users
	if [ ! "${IS_ROOT-}" ]; then
		_set_permissions
		if [ ! "${PASSWORD-}" ]; then
			for permission in ${USER_PERMISSIONS}; do
				if [ "${permission}" = "wheel" ]; then
					printf "\nWARNING:\nWheel permission is set, but this user has no password.\n"
					printf "You will not be able to run commands with 'sudo' without a password.\n"
					y_or_n "Set a password for this user?" default="yes" && _set_password
					break
				fi
			done
		fi

		if [ "${DESKTOP_ENVIRONMENT-}" ]; then
			y_or_n "Install a web browser?" default="yes" && _select_browser
		fi
	fi

	while :; do
		while :; do
			if [ ! "${PASSWORD-}" ] && [ ! "${AUTHORIZED_SSH_KEYS}" ]; then
				printf "\nWARNING: Neither a password nor an authorized SSH key was set for this user.\n"
				printf "At least one must be set, or the user will be inaccessible after installation completes.\n"
				printf "1. Password\n"
				printf "2. SSH key\n"
				printf "Enter the number corresponding to which you want to set: "
				read -r SELECTED
				SELECTED="$(printf "%s" "$SELECTED" | tr -dc '[:digit:]')"
				if [ ! "${SELECTED}" ] || [ "${SELECTED}" -gt 2 ]; then
					printf "Invalid selection. Try again\n"
					continue
				fi
				case "$SELECTED" in
				"1") _set_password ;;
				"2") _configure_ssh_keys ;;
				esac
			else
				break
			fi
		done
		printf "\nConfiguration for user:\n"
		printf "Username - %s\n" "$USERNAME"
		[ "${PASSWORD-}" ] && printf "Password - =*Redacted*=\n"
		[ "${WEB_BROWSER-}" ] && printf "Preferred Web Browser = %s\n" "$WEB_BROWSER"
		if [ "${AUTHORIZED_SSH_KEYS}" ]; then
			for key in $AUTHORIZED_SSH_KEYS; do
				printf "Authorized SSH key - %s\n" "$key"
			done
		fi
		if [ "${IS_ROOT-}" ]; then
			printf "Permission - System Administrator\n\n"
		elif [ "${USER_PERMISSIONS-}" ]; then
			for permission in $USER_PERMISSIONS; do
				printf "Permission - %s\n" "$permission"
			done
		else
			printf "Permission - None\n\n"
		fi

		printf "\n"
		y_or_n "Are you satisfied with the current configuration?" default="yes" && break
		clear
		OPTIONS="Username|Password|Permissions|Authorized Keys"
		[ "${WEB_BROWSER-}" ] && OPTIONS="$OPTIONS""|Web Browser"
		IFS='|'
		SELECTED="$(
			for option in $OPTIONS; do
				printf "%s\n" "$option"
			done | fzf \
				--disabled \
				--border \
				--border-label-pos 1:bottom \
				--border-label="Which do you wish to change? (Press esc or Ctrl+C to continue)"
		)"
		unset IFS
		case "${SELECTED-}" in
		"Username") _set_username ;;
		"Password") _set_password ;;
		"Web Browser") _select_browser ;;
		"Authorized Keys") _configure_ssh_keys ;;
		"Permissions") _set_permissions ;;
		*) continue ;;
		esac
	done

	USER_CONFIG_DIR="$HOST_CONFIG_DIR/users/$USERNAME"
	USER_CONFIG_FILE="$USER_CONFIG_DIR/default.nix"
	mkdir -p "$USER_CONFIG_DIR" || _errormsg "Failed to create $USER_CONFIG_DIR"

	printf "{ config, ... }:\n{" >"$USER_CONFIG_FILE"
	[ "${PASSWORD-}" ] && printf "sops.secrets.%s_password.neededForUsers = true;\n" "$USERNAME" >>"$USER_CONFIG_FILE"
	printf "users.users.%s = {\n" "$USERNAME" >>"$USER_CONFIG_FILE"
	[ "${PASSWORD-}" ] && printf "hashedPasswordFile = config.sops.secrets.%s_password.path;\n" "$USERNAME" >>"$USER_CONFIG_FILE"
	[ ! "${IS_ROOT-}" ] && printf "isNormalUser = true;\n" >>"$USER_CONFIG_FILE"
	if [ "${AUTHORIZED_SSH_KEYS-}" ]; then
		printf "openssh.authorizedKeys.keys = with config.keyring.ssh; [\n" >>"$USER_CONFIG_FILE"
		for key in $AUTHORIZED_SSH_KEYS; do
			printf "%s\n" "$key" >>"$USER_CONFIG_FILE"
		done
		printf "];\n" >>"$USER_CONFIG_FILE"
	fi

	if [ "${USER_PERMISSIONS-}" ]; then
		printf "extraGroups = [ " >>"$USER_CONFIG_FILE"
		for permission in $USER_PERMISSIONS; do
			case "$permission" in
			"wheel") printf "\"wheel\"\n" >>"$USER_CONFIG_FILE" ;;
			"networkmanager") printf "\"networkmanager\"\n" >>"$USER_CONFIG_FILE" ;;
			esac
		done
		printf "];\n" >>"$USER_CONFIG_FILE"
	fi

	printf "};\n}" >>"$USER_CONFIG_FILE"

	if [ "${WEB_BROWSER-}" ]; then
		sed -i '$ s/.$//' "$HOST_CONFIG_FILE"
		_debugmsg "Installing browser: $WEB_BROWSER"
		if grep -q "programs.$WEB_BROWSER" "$HOST_CONFIG_FILE"; then
			sed -i "s|\(installForUsers = [\)\([^\]]*\)|\1\n\t\"$USERNAME\"|" "$HOST_CONFIG_FILE"
		else
			printf "
				programs.%s = {
					enable = true;
					installGlobally = lib.mkDefault false;
					installForUsers = [
						\"%s\"
					];
				};
			}" "$WEB_BROWSER" "$USERNAME" >>"$HOST_CONFIG_FILE"
		fi
	fi

	_add_user "$USERNAME"

	printf "\nConfigured Users:\n"
	for user in $USERS; do
		printf "%s\n" "$user"
	done
	printf "\n"
	[ "${PASSWORD-}" ] && printf "%s_password: %s\n" "$USERNAME" "$(mkpasswd -s "$PASSWORD")" >>"$HOST_SECRETS_FILE"

	unset USERNAME PASSWORD WEB_BROWSER AUTHORIZED_SSH_KEYS USER_PERMISSIONS
	y_or_n "Add/Configure another user?" default="no" || break
done

# use the auto generated keys in the installer for the host ssh identity
cat /etc/ssh/ssh_host_ed25519_key.pub | sed "s|root@nixos-installer|root@$HOSTNAME|" >"$HOST_CONFIG_DIR/ssh_host_ed25519_key.pub"
cat /etc/ssh/ssh_host_rsa_key.pub | sed "s|root@nixos-installer|root@$HOSTNAME|" >"$HOST_CONFIG_DIR/ssh_host_rsa_key.pub"
sed -i '$ s/.$//' "$HOST_CONFIG_FILE"

printf "\nenvironment = {
    etc = {
      \"ssh/ssh_host_ed25519_key.pub\".source = ./ssh_host_ed25519_key.pub;
      \"ssh/ssh_host_rsa_key.pub\".source = ./ssh_host_rsa_key.pub;
    };
};

sops.secrets = {
	ssh_host_ed25519_key.path = \"/etc/ssh/ssh_host_ed25519_key\";
	ssh_host_rsa_key.path = \"/etc/ssh/ssh_host_rsa_key\";
};\n}" >>"$HOST_CONFIG_FILE"

_format_secret() {
	cat "$1" | while read -r line; do
		printf "  %s\n" "$line" >>"$HOST_SECRETS_FILE"
	done
}

printf "\nssh_host_ed25519_key: |\n" >>"$HOST_SECRETS_FILE"
_format_secret /etc/ssh/ssh_host_ed25519_key
printf "\nssh_host_rsa_key: |\n" >>"$HOST_SECRETS_FILE"
_format_secret /etc/ssh/ssh_host_rsa_key

# encrypt secrets file
if [ -e "$HOST_SECRETS_FILE" ]; then
	sops --config "$CONFIG_ROOT/.sops.yaml" -e -i "$HOST_SECRETS_FILE" || _errormsg "Failed to encrypt the secrets file for this host."
fi

find "$CONFIG_ROOT" -type f -not -path '*/.*' | while read -r file; do
	case "$file" in
	*".nix") nixfmt "$file" || printf "Warning: Failed to format nix file %s" "$file" ;;
	*) continue ;;
	esac
done

_install_nixos
